name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF Space
        run: |
          git remote add hf https://AbdullahKhanSherwani:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/AbdullahKhanSherwani/BlackBox
          git push hf main --force
